# Generated by Django 3.2.9 on 2022-01-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_sender_id_chat_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='unique_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
