# Generated by Django 3.2.9 on 2022-01-15 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_chat_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='sender',
        ),
    ]
