# Generated by Django 3.2.9 on 2022-02-05 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0006_alter_memebers_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='member',
            field=models.ForeignKey(default='tusharkhera', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memebers',
            name='group',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.group'),
        ),
    ]
