# Generated by Django 3.2.9 on 2022-02-05 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_memebers_members'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Memebers',
        ),
    ]
