# Generated by Django 3.2.9 on 2022-02-05 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0013_auto_20220205_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memebers',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.group'),
        ),
        migrations.AlterField(
            model_name='memebers',
            name='members',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
