# Generated by Django 3.2.9 on 2022-02-06 06:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0014_auto_20220205_1916'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Memebers',
            new_name='ChatList',
        ),
        migrations.RenameField(
            model_name='chatlist',
            old_name='members',
            new_name='user',
        ),
    ]
