# Generated by Django 3.2.9 on 2022-02-06 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20220206_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatlist',
            old_name='user',
            new_name='chat_user',
        ),
        migrations.AlterField(
            model_name='chat',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.group'),
        ),
    ]
