# Generated by Django 3.2.9 on 2022-02-06 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0020_auto_20220206_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatlist',
            name='chat_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatlist',
            name='grp',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='group',
            name='unique_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
