# Generated by Django 3.2.9 on 2022-02-06 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_auto_20220206_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatlist',
            name='grp',
        ),
    ]
