# Generated by Django 3.2.9 on 2022-02-06 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_remove_chatlist_grp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatList',
        ),
    ]
