# Generated by Django 3.2.9 on 2022-03-30 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_group_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_dp',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
